name: Validate Pull Request
on:
  pull_request_target:
jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: Namchee/conventional-pr@v0.13.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          close: false
          body: false
          issue: false
