# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Validate pull request contents

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  validate:
    name: Validate pull request contents

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install devDependencies
        run: pnpm install --dev --frozen-lockfile --ignore-scripts --workspace-root

      - name: Lint PR title
        run: echo ${{ toJSON(github.event.pull_request.title) }} | npx --no -- commitlint

      - name: Format PR title
        id: devmoji
        run: |
          TITLE=$(npx --no -- devmoji --format shortcode --text ${{ toJSON(github.event.pull_request.title) }})
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT

      - name: Update PR title if needed
        if: toJSON(github.event.pull_request.title) != toJSON(steps.devmoji.outputs.TITLE)
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.number }}
          title: ${{ toJSON(steps.devmoji.outputs.TITLE) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
